# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ns.grpc.protobufs.lang_detection import lang_detection_pb2 as ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2


class LanguageDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect = channel.unary_unary(
                '/LanguageDetector/detect',
                request_serializer=ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelRequest.SerializeToString,
                response_deserializer=ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelResponse.FromString,
                )


class LanguageDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect': grpc.unary_unary_rpc_method_handler(
                    servicer.detect,
                    request_deserializer=ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelRequest.FromString,
                    response_serializer=ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LanguageDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LanguageDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LanguageDetector/detect',
            ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelRequest.SerializeToString,
            ns_dot_grpc_dot_protobufs_dot_lang__detection_dot_lang__detection__pb2.LangModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
